image: archlinux
secrets:
  - 820d708b-337f-4ab6-9a33-b9c4d1469b57
packages:
  - rustup
sources:
  - https://git.sr.ht/~tudor/rwsh
tasks:
  - check_license: |
      for f in $(find . -iname '*.rs'); do
        grep "GNU General Public License" "$f" > /dev/null || exit 1
      done
  - setup: |
      rustup install stable
      rustup default stable
      export RUST_BACKTRACE=full
  - build: |
      cd rwsh
      cargo build --verbose
      cargo test --verbose
  - examples: |
      cd rwsh/examples
      ./run_examples.sh
  - push_to_github: |
      cd rwsh
      git push --all "https://tudurom:$(cat ~/.gh_pass)@github.com/tudurom/rwsh"
